### ISSUE TITLE
Ensure code chunks in all recipes are {.python} and {.r}

### ISSUE THREAD

**Issue by tnederlof** [posit-dev/connect-cookbook#66]
There is currently a mix of {.python}/{python} and {.r}/{r} used throughout the recipes. It would simplify things to take a pass and ensure they are all using the dot notation.

One example: https://github.com/posit-dev/connect-cookbook/blob/f476e62d8283e47a53cf0f058ea5761e7b10c285/content/content-by-user/index.qmd#L33

**Comment by toph-allen** [comment]
This was closed by #82 but didn't auto-close for some reason.
